[rospy.client][INFO] 2020-06-16 16:23:15,760: init_node, name[/obj_node], pid[9988]
[xmlrpc][INFO] 2020-06-16 16:23:15,769: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-06-16 16:23:15,770: Started XML-RPC server [http://jose-Lenovo-V110-15AST:45117/]
[rospy.init][INFO] 2020-06-16 16:23:15,772: ROS Slave URI: [http://jose-Lenovo-V110-15AST:45117/]
[rospy.impl.masterslave][INFO] 2020-06-16 16:23:15,773: _ready: http://jose-Lenovo-V110-15AST:45117/
[rospy.registration][INFO] 2020-06-16 16:23:15,784: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2020-06-16 16:23:15,785: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-06-16 16:23:15,873: registered with master
[rospy.rosout][INFO] 2020-06-16 16:23:15,873: initializing /rosout core topic
[rospy.rosout][INFO] 2020-06-16 16:23:15,887: connected to core topic /rosout
[rospy.simtime][INFO] 2020-06-16 16:23:15,889: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-06-16 16:23:16,126: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-06-16 16:23:16,477: topic[/ready_img] adding connection to [/show_img], count 0
[rospy.internal][INFO] 2020-06-16 16:23:17,023: topic[/obj_detector] adding connection to [/robot_move], count 0
[rospy.internal][INFO] 2020-06-16 16:23:17,031: topic[/robot_status] adding connection to [http://jose-Lenovo-V110-15AST:41831/], count 0
[rospy.internal][ERROR] 2020-06-16 16:23:50,222: Unable to initiate TCP/IP socket to jose-Lenovo-V110-15AST:39287 (http://jose-Lenovo-V110-15AST:41831/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-06-16 16:23:50,231: topic[/obj_detector] adding connection to [/robot_move], count 1
[rospy.internal][INFO] 2020-06-16 16:23:50,232: topic[/obj_detector] removing connection to /robot_move
[rospy.core][INFO] 2020-06-16 16:23:50,233: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-06-16 16:23:50,238: topic[/obj_detector] removing connection to /robot_move
[rospy.internal][INFO] 2020-06-16 16:23:50,239: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-06-16 16:23:50,239: topic[/ready_img] removing connection to /show_img
[rospy.internal][INFO] 2020-06-16 16:23:50,240: topic[/robot_status] removing connection to http://jose-Lenovo-V110-15AST:41831/
[rospy.impl.masterslave][INFO] 2020-06-16 16:23:50,240: signal-2
[rospy.core][INFO] 2020-06-16 16:23:50,378: signal_shutdown [atexit]
